working_dir: &working_dir ~/app

version: 2.1 
 
orbs: 
   
  python: circleci/python@1.2 
 
workflows: 
  sample:   
    jobs: 
      - job
 
jobs: 
  job:
    parallelism: 16
    docker: 
      - image: cimg/python:3.8 
     
    steps: 
      - checkout 
      - run: chmod +x ./install.sh
      - run: ./install.sh
